-- Run this once in Supabase SQL Editor. Create your first admin in
-- Authentication > Users, then execute: update public.profiles set is_admin=true
-- where id = '<that-auth-user-uuid>';
create extension if not exists pgcrypto;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, is_admin boolean not null default false, created_at timestamptz not null default now());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(id) values (new.id); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select coalesce((select is_admin from public.profiles where id = auth.uid()), false); $$;

create table if not exists public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, group_name text not null check (group_name in ('Plants','Other')), description text not null default '', image_url text not null default '', created_at timestamptz not null default now());
create table if not exists public.products (id uuid primary key default gen_random_uuid(), name text not null, category text not null, price numeric(10,2) not null check(price >= 0), images text[] not null default '{}', short_description text not null default '', description text not null default '', care_difficulty text not null default 'Easy', availability text not null default 'In Stock', uses text not null default '', growing_conditions text not null default '', sunlight text not null default 'Bright Indirect Light', watering text not null default '', soil_type text not null default '', fertilizer text not null default '', growth_tips text not null default '', maintenance_level text not null default 'Low', suitable_climate text not null default '', plant_size text not null default 'Standard', featured boolean not null default false, rating numeric(2,1), reviews_count integer, is_active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.store_settings (key text primary key, value jsonb not null, updated_at timestamptz not null default now());
create table if not exists public.orders (id uuid primary key default gen_random_uuid(), order_number text not null unique default ('PLN-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))), customer_name text not null, phone text not null, address text, items jsonb not null, total_amount numeric(10,2) not null check(total_amount >= 0), status text not null default 'Pending WhatsApp', created_at timestamptz not null default now());

alter table public.categories enable row level security; alter table public.products enable row level security; alter table public.store_settings enable row level security; alter table public.orders enable row level security; alter table public.profiles enable row level security;
create policy "public catalog" on public.categories for select using (true); create policy "public products" on public.products for select using (is_active); create policy "public settings" on public.store_settings for select using (true); create policy "anyone creates orders" on public.orders for insert with check (char_length(customer_name) between 1 and 120 and char_length(phone) between 6 and 30);
create policy "admins manage categories" on public.categories for all using (public.is_admin()) with check (public.is_admin()); create policy "admins manage products" on public.products for all using (public.is_admin()) with check (public.is_admin()); create policy "admins manage settings" on public.store_settings for all using (public.is_admin()) with check (public.is_admin()); create policy "admins read orders" on public.orders for select using (public.is_admin()); create policy "admins read profile" on public.profiles for select using (auth.uid() = id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values ('product-images','product-images',true,5242880,array['image/jpeg','image/png','image/webp']) on conflict (id) do update set public=true;
create policy "public product images" on storage.objects for select using (bucket_id='product-images'); create policy "admins upload product images" on storage.objects for insert to authenticated with check (bucket_id='product-images' and public.is_admin()); create policy "admins delete product images" on storage.objects for delete to authenticated using (bucket_id='product-images' and public.is_admin());
